# Title for the gitleaks configuration file.
title = "Custom Gitleaks configuration"

[extend]
# Use the default gitleaks config and disable only the generic-api-key rule
useDefault = true
disabledRules = ["generic-api-key"]
